//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderApp.DataFactory
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserExtension
    {
        public string AspNetUserId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string FirebaseToken { get; set; }
        public Nullable<bool> IsStaffCallNotification { get; set; }
        public Nullable<bool> IsNewOrderNotification { get; set; }
        public Nullable<bool> IsOrderConfirmNotification { get; set; }
        public Nullable<bool> IsOrderInProcessNotification { get; set; }
        public Nullable<bool> IsCheckedItemNotification { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Company Company { get; set; }
    }
}
